<?php
    $assetsVersion = '0.2';
    $this->headScript()
        ->prependFile($this->basePath() . '/js/chat.js?version=' . $assetsVersion);
?>

<?php $this->headScript()->captureStart() ?>
Chat.webSocketsUlr = '<?php echo $webSocketsUlr;?>';
Chat.addUrl = '<?php echo $this->url('chat', array('action'=>'add'));?>';
Chat.getEditFormUrl = '<?php echo $this->url('chat', array('action'=>'get-edit-form'));?>';
Chat.editUrl = '<?php echo $this->url('chat', array('action'=>'edit'));?>';
Chat.deleteUrl = '<?php echo $this->url('chat', array('action'=>'delete'));?>';
Chat.getListUrl = '<?php echo $this->url('chat', array('action'=>'get-list'));?>';
Chat.changeStatusUrl = '<?php echo $this->url('chat', array('action'=>'change-status'));?>';
Chat.createSocketConnection();

<?php $this->headScript()->captureEnd() ?>

<div class="online-status">
    <div class="online-status-offline"><span class="label label-default"><span class="glyphicon glyphicon-remove"></span> Offline</span></div>
    <div class="online-status-online"><span class="label label-success"><span class="glyphicon glyphicon-ok"></span> Online</span></div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Time</th>
            <th>Message</th>
        </tr>
    </thead>
    <tbody class="chat-items">
        <?php echo $this->render('chat/chat/messages'); ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2">
                <p><?php echo $this->translate('Add new:'); ?></p>
                <div class="chat-add-form">
                    <?php echo $this->render('chat/chat/edit-form', array('editForm' => $addForm)); ?>
                </div>
                <p>&nbsp;</p>
                <a href="javascript: void(0);" class="btn btn-default btn-success" onclick="Chat.add();"><span class="glyphicon glyphicon-ok"></span></a>
            </td>
        </tr>
    </tbody>
</table>
