<?php
    $assetsVersion = '0.2';
    $this->headScript()
        ->prependFile($this->basePath() . '/js/shopping-list.js?version=' . $assetsVersion);
?>

<?php $this->headScript()->captureStart() ?>
ShoppingList.webSocketsUlr = '<?php echo $webSocketsUlr;?>';
ShoppingList.addUrl = '<?php echo $this->url('shopping-list', array('action'=>'add'));?>';
ShoppingList.getEditFormUrl = '<?php echo $this->url('shopping-list', array('action'=>'get-edit-form'));?>';
ShoppingList.editUrl = '<?php echo $this->url('shopping-list', array('action'=>'edit'));?>';
ShoppingList.deleteUrl = '<?php echo $this->url('shopping-list', array('action'=>'delete'));?>';
ShoppingList.getListUrl = '<?php echo $this->url('shopping-list', array('action'=>'get-list'));?>';
ShoppingList.changeStatusUrl = '<?php echo $this->url('shopping-list', array('action'=>'change-status'));?>';
ShoppingList.createSocketConnection();

<?php $this->headScript()->captureEnd() ?>

<div class="online-status">
    <div class="online-status-offline"><span class="label label-default"><span class="glyphicon glyphicon-remove"></span> Offline</span></div>
    <div class="online-status-online"><span class="label label-success"><span class="glyphicon glyphicon-ok"></span> Online</span></div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th class="shopping-list-actions">Actions</th>
        </tr>
    </thead>
    <tbody class="shopping-list-items">
        <?php echo $this->render('shopping-list/shopping-list/list'); ?>
    </tbody>
    <tbody>
        <tr>
            <td>
                <p><?php echo $this->translate('Add new:'); ?></p>
                <div class="shopping-list-add-form">
                    <?php echo $this->render('shopping-list/shopping-list/edit-form', array('editForm' => $addForm)); ?>
                </div>
            </td>
            <td class="shopping-list-actions">
                <p>&nbsp;</p>
                <a href="javascript: void(0);" class="btn btn-default btn-success" onclick="ShoppingList.add();"><span class="glyphicon glyphicon-ok"></span></a>
            </td>
        </tr>
    </tbody>
</table>
