<?php foreach ($shoppingList as $shoppingListItem) { ?>
    <tr class="shopping-list-row">
        <td>
            <div class="shopping-list-row-data shopping-list-row-data-<?php echo $this->escapeHtml($shoppingListItem->id);?>">
                <span class="<?php if ($shoppingListItem->isDone()) { ?>shopping-list-title-done<?php } ?>">
                    <?php echo $this->escapeHtml($shoppingListItem->title);?>
                </span>
                <div class="shopping-list-row-loading shopping-list-row-loading-<?php echo $this->escapeHtml($shoppingListItem->id);?>" title="Loading..."></div>
            </div>
            <div class="shopping-list-row-form shopping-list-row-form-<?php echo $this->escapeHtml($shoppingListItem->id);?>">
            </div>
            <div class="shopping-list-row-editing shopping-list-row-editing-<?php echo $this->escapeHtml($shoppingListItem->id);?>">
                <span class="glyphicon glyphicon-pencil"></span> Editing...
            </div>
        </td>
        <td class="shopping-list-actions">
            <div class="shopping-list-actions-default shopping-list-actions-default-<?php echo $shoppingListItem->id ?>">
                <?php if ($shoppingListItem->isDone()) { ?>
                    <a href="javascript: void(0);" class="btn btn-default btn-default" onclick="ShoppingList.changeStatus(<?php echo $shoppingListItem->id ?>, 'undone');" title="Undone"><span class="glyphicon glyphicon-check"></span></a>
                <?php } else { ?>
                    <a href="javascript: void(0);" class="btn btn-default btn-success" onclick="ShoppingList.changeStatus(<?php echo $shoppingListItem->id ?>, 'done');" title="Done"><span class="glyphicon glyphicon-check"></span></a>
                <?php } ?>
                <a href="javascript: void(0);" onclick="ShoppingList.getEditForm(<?php echo $shoppingListItem->id ?>);" class="btn btn-default btn-primary" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
                <a href="javascript: void(0);" onclick="ShoppingList.delete(<?php echo $shoppingListItem->id ?>);" class="btn btn-default btn-danger" title="Delete"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
            <div class="shopping-list-actions-edit shopping-list-actions-edit-<?php echo $shoppingListItem->id ?>">
                <a href="javascript: void(0);" class="btn btn-default btn-success" onclick="ShoppingList.edit(<?php echo $shoppingListItem->id ?>);" title="Save"><span class="glyphicon glyphicon-ok"></span></a>
                <a href="javascript: void(0);" class="btn btn-default btn-default" onclick="ShoppingList.cancelEdit(<?php echo $shoppingListItem->id ?>);" title="Cancel"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
        </td>
    </tr>
<?php }; ?>
