_chat:
    resource: "@MarichatChatBundle/Controller/ChatController.php"
    type:     annotation
    prefix:   /chat

_chat_secured:
    resource: "@MarichatChatBundle/Controller/SecuredController.php"
    type:     annotation
    prefix:   /chat
